INSERT INTO UsedElectronics (name, price, description, release_year, condition) VALUES
('Samsung Galaxy S10', 299.99, 'A powerful smartphone with a stunning display and advanced camera capabilities.', 2019, 'Good'),
('Apple MacBook Air 2017', 599.99, 'Lightweight and portable laptop with a sleek design and reliable performance.', 2017, 'Very Good'),
('Sony WH-1000XM3 Headphones', 199.99, 'Noise-cancelling over-ear headphones with superior sound quality and comfort.', 2018, 'Excellent'),
('Dell XPS 13', 899.99, 'Compact and powerful ultrabook with a stunning display and long battery life.', 2019, 'Good'),
('Canon EOS Rebel T7i', 499.99, 'A versatile DSLR camera with impressive image quality and user-friendly features.', 2017, 'Very Good'),
('Apple iPad Pro 11-inch', 649.99, 'High-performance tablet with a brilliant display and advanced features.', 2018, 'Excellent'),
('Microsoft Surface Pro 6', 749.99, '2-in-1 detachable laptop with versatile functionality and strong performance.', 2018, 'Good'),
('Bose QuietComfort 35 II', 179.99, 'Noise-cancelling wireless headphones with superior sound and comfort.', 2017, 'Very Good'),
('Google Pixel 3', 299.99, 'Smartphone with excellent camera quality and a clean Android experience.', 2018, 'Good'),
('Samsung Galaxy Tab S6', 499.99, 'Powerful tablet with a stunning display and versatile S Pen functionality.', 2019, 'Excellent'),
('Apple Watch Series 4', 349.99, 'Smartwatch with advanced health tracking features and a sleek design.', 2018, 'Good'),
('HP Spectre x360', 999.99, 'Premium 2-in-1 laptop with a flexible design and powerful performance.', 2019, 'Very Good'),
('Sony Alpha a6000', 449.99, 'Compact mirrorless camera with fast autofocus and excellent image quality.', 2014, 'Good'),
('JBL Charge 4', 129.99, 'Portable Bluetooth speaker with powerful sound and long battery life.', 2018, 'Very Good'),
('Apple iPhone XR', 399.99, 'Smartphone with a vibrant display and advanced camera capabilities.', 2018, 'Excellent'),
('Asus ROG Strix GL502VS', 1199.99, 'High-performance gaming laptop with a powerful GPU and smooth display.', 2017, 'Good'),
('Amazon Kindle Oasis', 179.99, 'E-reader with a high-resolution display and waterproof design.', 2017, 'Very Good'),
('Fitbit Charge 3', 99.99, 'Fitness tracker with heart rate monitoring and sleep tracking.', 2018, 'Good'),
('Nintendo Switch', 249.99, 'Hybrid gaming console with versatile gameplay options and a wide game library.', 2017, 'Very Good'),
('GoPro Hero 7 Black', 249.99, 'Action camera with excellent video stabilization and rugged design.', 2018, 'Good'),
('Logitech MX Master 3', 79.99, 'Ergonomic wireless mouse with advanced features and precision tracking.', 2019, 'Very Good'),
('Dyson V10 Absolute', 399.99, 'Powerful cordless vacuum cleaner with advanced suction technology.', 2018, 'Excellent'),
('Garmin Forerunner 235', 149.99, 'GPS running watch with heart rate monitoring and smart notifications.', 2015, 'Good'),
('Sony PlayStation 4 Pro', 349.99, 'Enhanced gaming console with 4K capabilities and improved performance.', 2016, 'Very Good'),
('LG C9 OLED TV', 1499.99, '4K OLED TV with stunning picture quality and smart TV features.', 2019, 'Excellent'),
('DJI Mavic Air', 599.99, 'Compact drone with high-quality camera and advanced flight features.', 2018, 'Good'),
('Apple AirPods Pro', 199.99, 'Wireless earbuds with active noise cancellation and superior sound.', 2019, 'Very Good'),
('Nikon D750', 999.99, 'Full-frame DSLR camera with excellent image quality and versatile features.', 2014, 'Good'),
('Razer Blade 15', 1599.99, 'High-performance gaming laptop with a sleek design and powerful specs.', 2018, 'Very Good'),
('Samsung Galaxy Note 9', 399.99, 'Smartphone with a large display and advanced S Pen functionality.', 2018, 'Excellent'),
('Bose SoundLink Revolve+', 199.99, 'Portable Bluetooth speaker with 360-degree sound and long battery life.', 2017, 'Good'),
('Apple MacBook Pro 2018', 1199.99, 'Powerful laptop with a Retina display and advanced features.', 2018, 'Very Good'),
('Canon PowerShot G7 X Mark II', 499.99, 'Compact camera with impressive image quality and user-friendly controls.', 2016, 'Good'),
('Microsoft Xbox One X', 349.99, 'High-performance gaming console with 4K capabilities and a large game library.', 2017, 'Very Good'),
('Samsung Gear S3 Frontier', 199.99, 'Smartwatch with a rugged design and advanced fitness tracking.', 2016, 'Good'),
('Lenovo ThinkPad X1 Carbon', 899.99, 'Ultrabook with a durable design and powerful performance.', 2019, 'Very Good'),
('Apple iPhone 8 Plus', 349.99, 'Smartphone with a dual camera system and reliable performance.', 2017, 'Good'),
('Anker PowerCore 20100', 49.99, 'Portable charger with high capacity and fast charging capabilities.', 2016, 'Very Good'),
('Sony RX100 VI', 899.99, 'Compact camera with a long zoom lens and excellent image quality.', 2018, 'Excellent'),
('Samsung Galaxy Watch Active 2', 229.99, 'Smartwatch with advanced health tracking and a sleek design.', 2019, 'Good'),
('Dell Inspiron 15 7000', 749.99, 'Versatile laptop with a powerful processor and ample storage.', 2019, 'Very Good'),
('Google Home Max', 249.99, 'Smart speaker with powerful sound and integrated Google Assistant.', 2017, 'Good'),
('Fujifilm X-T3', 1299.99, 'Mirrorless camera with excellent image quality and advanced features.', 2018, 'Very Good'),
('Beats Solo3 Wireless', 149.99, 'On-ear headphones with excellent sound quality and long battery life.', 2016, 'Good'),
('HP Envy 13', 699.99, 'Stylish and powerful ultrabook with a bright display and long battery life.', 2019, 'Very Good'),
('Apple TV 4K', 179.99, 'Streaming device with 4K HDR capabilities and a wide range of content.', 2017, 'Excellent'),
('Logitech G Pro Wireless', 129.99, 'Wireless gaming mouse with advanced features and a lightweight design.', 2018, 'Good'),
('Samsung Galaxy S9+', 349.99, 'Smartphone with a large display and advanced camera features.', 2018, 'Very Good'),
('Sony HT-ST5000', 999.99, 'High-end soundbar with Dolby Atmos and excellent audio quality.', 2017, 'Excellent'),
('Asus ZenBook 14', 849.99, 'Compact ultrabook with a sleek design and strong performance.', 2019, 'Good'),
('Amazon Echo Show 2nd Gen', 179.99, 'Smart display with Alexa and a vibrant screen.', 2018, 'Very Good'),
('Nikon Z6', 1599.99, 'Full-frame mirrorless camera with excellent image quality and features.', 2018, 'Good'),
('Bose SoundSport Free', 149.99, 'Truly wireless earbuds with excellent sound quality and comfort.', 2017, 'Very Good'),
('Microsoft Surface Book 2', 1199.99, 'Versatile 2-in-1 laptop with powerful performance and a detachable screen.', 2017, 'Good'),
('Google Pixelbook', 899.99, 'High-end Chromebook with a sleek design and strong performance.', 2017, 'Very Good'),
('Canon EOS M50', 599.99, 'Compact mirrorless camera with excellent image quality and 4K video.', 2018, 'Good'),
('Sony PlayStation VR', 199.99, 'Virtual reality headset with immersive gaming experiences.', 2016, 'Very Good'),
('Samsung Galaxy Buds', 99.99, 'Wireless earbuds with good sound quality and comfortable fit.', 2019, 'Good'),
('Apple Mac Mini 2018', 799.99, 'Compact desktop computer with powerful performance and a sleek design.', 2018, 'Excellent'),
('Fitbit Versa 2', 129.99, 'Smartwatch with advanced health tracking and a sleek design.', 2019, 'Good'),
('LG Gram 15', 1099.99, 'Lightweight and powerful ultrabook with a large display and long battery life.', 2018, 'Very Good'),
('Sony Alpha a6400', 899.99, 'Mirrorless camera with fast autofocus and excellent image quality.', 2019, 'Excellent'),
('Bose SoundLink Mini II', 129.99, 'Portable Bluetooth speaker with impressive sound quality and compact design.', 2015, 'Good'),
('Dell G5 15', 799.99, 'Gaming laptop with strong performance and a sleek design.', 2019, 'Very Good'),
('Amazon Fire HD 10', 149.99, 'Affordable tablet with a large display and good performance.', 2019, 'Good'),
('DJI Osmo Pocket', 299.99, 'Compact gimbal camera with excellent video stabilization and 4K capabilities.', 2018, 'Very Good'),
('Samsung Q90R QLED TV', 1999.99, '4K QLED TV with stunning picture quality and smart TV features.', 2019, 'Excellent'),
('GoPro Hero 8 Black', 299.99, 'Action camera with advanced stabilization and rugged design.', 2019, 'Good'),
('Apple iPhone SE (2nd generation)', 299.99, 'Compact smartphone with powerful performance and a great camera.', 2020, 'Very Good'),
('Lenovo Yoga C940', 1199.99, '2-in-1 laptop with a flexible design and strong performance.', 2019, 'Excellent'),
('Canon EOS 90D', 1199.99, 'DSLR camera with impressive image quality and advanced features.', 2019, 'Good'),
('Bose Home Speaker 500', 299.99, 'Smart speaker with powerful sound and built-in voice assistants.', 2018, 'Very Good'),
('Apple iPad Mini 5', 349.99, 'Compact and powerful tablet with a brilliant display and Apple Pencil support.', 2019, 'Excellent'),
('Sony WH-CH700N', 99.99, 'Affordable noise-cancelling headphones with good sound quality and comfort.', 2018, 'Good'),
('Dell XPS 15', 1399.99, 'High-performance laptop with a stunning 4K display and powerful specs.', 2019, 'Very Good'),
('Nikon D850', 2499.99, 'High-resolution DSLR camera with excellent image quality and features.', 2017, 'Good'),
('Jabra Elite 65t', 119.99, 'Truly wireless earbuds with great sound quality and comfortable fit.', 2018, 'Very Good'),
('Apple Watch Series 3', 199.99, 'Smartwatch with fitness tracking and cellular capabilities.', 2017, 'Good'),
('Microsoft Surface Go', 399.99, 'Affordable and portable 2-in-1 laptop with a versatile design.', 2018, 'Very Good'),
('Sony Xperia XZ3', 299.99, 'Smartphone with a beautiful OLED display and advanced camera features.', 2018, 'Good'),
('Samsung Galaxy Tab S4', 349.99, 'Powerful tablet with a large display and S Pen functionality.', 2018, 'Very Good'),
('Apple iPhone X', 599.99, 'Smartphone with a stunning OLED display and advanced camera system.', 2017, 'Excellent'),
('DJI Mavic Pro', 799.99, 'Compact drone with a high-quality camera and advanced flight features.', 2016, 'Good'),
('Google Pixel 4 XL', 499.99, 'Smartphone with a brilliant display and excellent camera quality.', 2019, 'Very Good'),
('Bose QuietComfort 20', 199.99, 'In-ear noise-cancelling headphones with excellent sound quality and comfort.', 2015, 'Good'),
('Lenovo Legion Y540', 999.99, 'Gaming laptop with strong performance and a sleek design.', 2019, 'Very Good'),
('Canon EOS R', 1799.99, 'Full-frame mirrorless camera with excellent image quality and features.', 2018, 'Good'),
('Apple iPad Air (3rd generation)', 449.99, 'Lightweight and powerful tablet with a brilliant display and Apple Pencil support.', 2019, 'Excellent'),
('Samsung Galaxy S8', 299.99, 'Smartphone with a stunning display and advanced camera features.', 2017, 'Good'),
('Dell Latitude 7490', 1199.99, 'Business laptop with strong performance and a durable design.', 2018, 'Very Good'),
('Sony PlayStation 5', 499.99, 'Next-generation gaming console with advanced features and stunning graphics.', 2020, 'Excellent'),
('GoPro Hero 9 Black', 399.99, 'Action camera with advanced stabilization and 5K video capabilities.', 2020, 'Good'),
('Apple iPhone 11 Pro', 899.99, 'Smartphone with a brilliant display and advanced camera system.', 2019, 'Very Good'),
('Asus ROG Phone 2', 699.99, 'High-performance gaming smartphone with a large display and powerful specs.', 2019, 'Good'),
('Microsoft Surface Laptop 3', 999.99, 'Stylish and powerful laptop with a great display and performance.', 2019, 'Very Good'),
('Fujifilm X100F', 1299.99, 'Compact camera with excellent image quality and classic design.', 2017, 'Good'),
('Samsung Galaxy Watch', 199.99, 'Smartwatch with advanced health tracking and a sleek design.', 2018, 'Very Good'),
('Apple AirPods 2', 129.99, 'Wireless earbuds with excellent sound quality and seamless connectivity.', 2019, 'Good'),
('Dell Alienware m15', 1499.99, 'High-performance gaming laptop with powerful specs and a sleek design.', 2019, 'Very Good'),
('Nikon Z50', 849.99, 'Compact mirrorless camera with excellent image quality and features.', 2019, 'Good');
